### ISSUE TITLE
Error: wiz: graphql: Cannot query field "action" on type "ServiceTicket". (SQLSTATE HV000)

### ISSUE THREAD

**Issue by sycophantic** [turbot/steampipe-plugin-wiz#22]
**Describe the bug**
Execute `select id from wiz_issue;` and it returns `Error: wiz: graphql: Cannot query field "action" on type "ServiceTicket". (SQLSTATE HV000)`

**Steampipe version (`steampipe -v`)**
v0.21.4

**Plugin version (`steampipe plugin list`)**
v0.2.0

**To reproduce**
`select id from wiz_issue;`

**Expected behavior**
A list of issues.

**Additional context**
I granted every read: permission to the oauth tokens and others queries work on other tables.

**Comment by jlgore** [comment]
I am seeing something similar on my end. Same version numbers as above. Will attempt to troubleshoot more and come back with some answers!

**Comment by misraved** [comment]
Apologies for the delayed response @sycophantic and @jlgore!!

The GraphQL query used to retrieve the Wiz issues had changed since we had initially released the plugin.

The fix involved removing the `action` subfield from the `ServiceTickets` header in the GraphQL query.

Please feel free to test the fixes using the latest Wiz plugin.

Happy to help if you have questions or if the fix doesn't work as expected 👍 !!

**Comment by sycophantic** [comment]
I created a PR, one of the instances was missed.

**Comment by nogarab** [comment]
Hello,
I am still getting this bug with the latest plugin versions (`0.3.0`, `1.0.0`). 
even when selecting columns other than `service_tickets`.
are you able to query this table now? would appreciate your assistance, thanks a lot 🙏
